Vagrant.configure(2) do |config|
  config.vm.box = "lucid64_ansible-git-docker"
  config.vm.synced_folder "shell/", "/vagrant" 
  config.vm.provision :shell, :inline => <<-HEREDOC
    ansible-playbook /vagrant/ansible.playbook
  HEREDOC
end

