
# vagrant layer 
# adds all the goodies one wants in a Vagrant setup

---
- hosts: localhost
  remote_user: root
  sudo: no
  tasks:

  - name: copy private key
    copy:
      src:   /vagrant/id_rsa
      dest:  /home/vagrant/.ssh/git.id_rsa
      owner: vagrant
      group: vagrant
      mode:  0600

  - name: copy public key
    copy:
      src:   /vagrant/id_rsa.pub
      dest:  /home/vagrant/.ssh/git.id_rsa.pub
      owner: vagrant
      group: vagrant
      mode:  0644

  - name: copy ssh config
    copy:
      src:   /vagrant/ssh-config
      dest:  /home/vagrant/.ssh/config
      owner: vagrant
      group: vagrant
      mode:  0644

  - name: create and/or adjust metadata of .ansible/ folder
    file:
      name:    /home/vagrant/.ansible/
      state:   directory
      owner:   vagrant
      group:   vagrant
      recurse: yes

  - name: create ~vagrant/src/ folder
    file:
      name:  ~vagrant/src/
      state: directory
      owner: vagrant
      group: vagrant
      mode:  0755

  - name: add vagrant user to docker group
    user:
      name:   vagrant
      groups: docker
      append: yes

  - name: enable users in docker group to run docker without sudo
    lineinfile:
      dest:     /etc/sudoers.d/docker
      owner:    root
      group:    root
      mode:     0440
      line:     'docker ALL=NOPASSWD: /usr/bin/docker'
      state:    present
      create:   yes
      validate: 'visudo -cf %s'

