Vagrant.configure(2) do |config|
  config.vm.box_url="https://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "shell/", "/vagrant" 
  config.vm.provision :shell, :inline => <<-HEREDOC
    ansible localhost -m apt -a 'name=software-properties-common state=latest update_cache=yes' ||
      apt-get -y install software-properties-common
    ansible localhost -m apt_repository -a "repo='ppa:ansible/ansible' state=present" || 
      apt-add-repository ppa:ansible/ansible
    ansible localhost -m apt -a 'name=ansible state=latest update_cache=yes' ||
       { apt-get update ; apt-get -y install ansible ; }
    ansible localhost -m apt -a 'name=git state=present'
    ansible localhost -m apt -a 'name=git-flow state=present'
    ansible localhost -m apt -a 'name=apt-transport-https state=present'
    ansible localhost -m apt_repository -a "repo='deb https://get.docker.com/ubuntu docker main' state=present"
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 36A1D7869245C8950F966E92D8576A8BA88D21E9
    ansible localhost -m apt -a 'name=lxc-docker-1.6.0 state=present update_cache=yes'
    ansible localhost -m copy -a "src=/vagrant/id_rsa dest=~/.ssh/git.id_rsa owner=vagrant group=vagrant mode=0600"
    ansible localhost -m copy -a "src=/vagrant/id_rsa.pub dest=~/.ssh/git.id_rsa.pub owner=vagrant group=vagrant mode=0644"
    ansible localhost -m copy -a "src=/vagrant/ssh-config dest=~/.ssh/config owner=vagrant group=vagrant mode=0644"
  HEREDOC
end



