Vagrant.configure(2) do |config|
  config.vm.box_url="https://vagrantcloud.com/ubuntu/boxes/trusty64"
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder "shell/", "/vagrant" 
  config.vm.provision :shell, :inline => <<-HEREDOC
    ansible localhost -m apt -a 'name=software-properties-common state=latest update_cache=yes' ||
      apt-get -y install software-properties-common
    ansible localhost -m apt_repository -a "repo='ppa:ansible/ansible' state=present" || 
      apt-add-repository -y ppa:ansible/ansible
    ansible localhost -m apt -a 'name=ansible state=latest update_cache=yes' ||
       { apt-get update ; apt-get -y install ansible ; }
    ansible-playbook /vagrant/ansible.playbook
  HEREDOC
end
